config/routes.rb
Workflow::Application.routes.draw do

  devise_for :users do get '/users/sign_out' => 'devise/sessions#destroy' end
  
  
  
  match '/users/sign_in' => redirect('/')  
    
  get "workflow_item/allworkflowitems"
  
  post "workflow_item/load"
  post "workflow_item/newWorkflowitemAdded"
  
  get "workflow_item/show"
  
  post "workflow_item/formsubmit"
  post "workflow_item/clearSession"
  
  post "workflow_item/runTheJobsNow"
  post "workflow_item/newConnectionAdded"
  
  post "workflow_item/getJobStatuses"
  
  post "workflow_item/getJobOutput"
  post "workflow_item/startnewjob"
  
  post "workflow_item/savethejob"
  post "workflow_item/gethtmlforwidget"
  
  
  get "listalljobs/alljobs"
  get "listalljobs/get_all_jobs"
  
  get "/listalljobs/loadjobdetails"
  
  post "workflow_item/createShellCommands"
  
  post "/workflow_item/test_data_recieved"
  
  post "/workflow_item/saveUiCoordinates"
  
  post "/workflow_item/restorejob"
  
  post "/workflow_item/getJobsToRestore"
  
  post "/workflow_item/retrieve_notifications"
  
  post "/workflow_item/removeWorkflowitem"
  
  post "/workflow_item/create_form_for_job_name"
  
  get "/add_workflowitem/create_new_workflowitem"
  
  get "/add_workflowitem/create"
  
  post "add_workflowitem/create_new_workflowitem_formsubmit"
  
  post "add_workflowitem/delete"
  
  

   root :to => 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/helpers/home_helper.rb
module HomeHelper
  
  
  
  def resource_name
    :user
  end
 
  def resource
    @resource ||= User.new
  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
  
  
  
end

app/views/home/index.html.erb
<html style="height:100%">
	
<body style="background:white;height:100%;">
		
	





	<div style="background:gray;height:80%;width:960px;margin-left: auto;margin-right: auto;margin-top:40px;border-radius:30px;">
	
		
			<div id="left" style="height:100%;width:300px;float: left">
				
		
		
			<div id="signin" style="padding:20px;margin:20px;border:1px solid black;display:block;width:200px;">
				
				<% if user_signed_in? %>
					Welcome <%= current_user.email %>. 
					
					
					<div id="buttonspanel" style="display:inline-block;border-radius: 5px">
					
					<div style="width:200px;height:50px;border:1px solid;background:#5E94FF;text-align:center;margin-top:20px;margin-bottom:20px;border-radius: 5px" onclick="window.location='/workflow_item/show'">
						<p style="text-align: center;padding:15px;font-size: 1.4em">CreateWorkFlow</p>
					</div>
					
					<div style="width:200px;height:50px;border:1px solid;background:#5E94FF;border-radius: 5px;" onclick="window.location='/listalljobs/alljobs'">
						<p style="text-align: center;padding:15px;font-size: 1.4em">View Outputs</p>
					</div>
					<div id="filler" style="height:20px";> </div>
					<div style="width:200px;height:50px;border:1px solid;background:#5E94FF;border-radius: 5px;" onclick="alert('Not available in demo')">
						<p style="text-align: center;padding:15px;font-size: 1.4em">Upload Data File</p>
					</div>
					
					<div id="filler" style="height:20px";> </div>
					<div style="width:200px;height:50px;border:1px solid;background:#5E94FF;border-radius: 5px;" onclick="window.location='/add_workflowitem/create_new_workflowitem'">
						<p style="text-align: center;padding:15px;font-size: 1.4em">Manage Tools</p>
					</div>
					<!--  http://www.surveymonkey.com/s/JD5H53B -->
					
					<div id="filler" style="height:20px";> </div>
					<div style="width:200px;height:50px;border:1px solid;background:#5E94FF;border-radius: 5px;" ">
						<p style="text-align: center;padding:15px;font-size: 1.4em"><a href="http://www.surveymonkey.com/s/JD5H53B" target="_blank"><font color="black">15 seconds feedback </font></a></p>
					</div>
					
				</div>
					
				<% else %>
					
					
					<%= form_for("user", :url => user_session_path) do |f| %>
				
					  <div><%= f.label :email %><br />
					  <%= f.text_field :email %>
					  </div>
					  
					  <div><%= f.label :password %><br />
					  <%= f.password_field :password %>
					  </div>
					  <br />
					  <%= f.check_box :remember_me %>
					  <%= f.label :remember_me %>
					  <br />
					  <br />
					  <%= f.submit 'Sign in' %>
					  <br />
					  <%= link_to "Forgot your password?", new_password_path('user') %>
					  <br />
					  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
				<% end %>
					
				 <% end %>
				
			</div>
		</div>
		
		
		
		<div id="right" style="height:93%;border:1px solid blue;width:600px;float: right;margin:20px;border-radius: 10px;background:#E8E8E8">
			
		</div>
		
		<!--<a href="/workflow_item/show">Create Automation job</a> -->
		
		
		
		
		
		

	</div>
	


</body>

</html>